n1=int(input("Enter the first number:"))
n2=int(input("Enter the second number:"))
print("sum:",(n1+n2))
print("Diff:",(n1-n2))
print("Mul:",(n1*n2))
print("Div:",(n1/n2))
print("Mod:",(n1%n2))
print("Exp:",(n1**n2))
print("positive Floor Division:",n1//n2)
print("Negative Floor Division:",(-n1//n2))
